### PR TITLE
feat/gh actions pipelines

### PR DESCRIPTION
**Pull request by mmpetarpeshev**

### CODE REVIEW

**Comment by marc0olo** [comment]
@thepiwo can you maybe have a quick look over this before we merge it?

**Comment by mmpetarpeshev** [comment]
I have to made one fix , to remove one file . Just approve or comment and I will merge

**Comment by marc0olo** [comment]
I can't really judge that right now. I would feel better if somebody like @thepiwo, @kenodressel or @dincho can just have a quick look and give the "ok" :-)

**Review by thepiwo — APPROVED** [review]
good if it works

**Pull request merged**
